### ISSUE TITLE
NLog Target for writing to AppCenter

### ISSUE THREAD

**Issue by snakefoot** [damienaicheh/LogProject#1]
@damienaicheh You can make NLog write to AppCenter for you using [NLog.Targets.AppCenter](https://www.nuget.org/packages/NLog.Targets.AppCenter)

NLog AppCenter Target allows you to capture additional log-context information easily without having to add it directly to the log-message. See also: https://github.com/NLog/NLog.AzureAppCenter

**Comment by damienaicheh** [comment]
Oh thanks ! I never notice that I will look at it, it's very interesting! That's a good information :) It's a new cool feature !
